config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'portfolio' => 'static_pages#portfolio'
  get 'contact' => 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def portfolio
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Joey Poon"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to image_tag('github.png', alt: "Github Logo"), 'https://github.com/joeypoon' %></li>
      <li><%= link_to image_tag('twitter.png', alt: "Twitter Logo"), 'https://twitter.com/JoeyFPoon' %></li>
      <li><%= link_to image_tag('linkedin.png', alt: "LinkedIn Logo"), 'https://www.linkedin.com/in/joeypoon' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Joey Poon", root_path, id: "logo" %>
    <nav>
      <ul class = "nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Blog", 'http://joeypoon.com/blog' %></li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1 class="center">Contact</h1>
<p>Contact Me</p>

app/views/static_pages/home.html.erb
<h1 class="center">Home</h1>
<p>American Apparel lumbersexual gluten-free tattooed, photo booth paleo artisan viral next level you probably haven't heard of them. Occupy viral Truffaut drinking vinegar Intelligentsia listicle chambray, blog synth. Trust fund sriracha Tumblr DIY, meditation Pinterest Austin mixtape pickled raw denim McSweeney's. Taxidermy ennui leggings, farm-to-table ugh actually migas distillery Vice church-key. Banksy scenester street art fixie, asymmetrical blog letterpress ugh. Viral keffiyeh normcore, +1 meggings lomo selvage. Meggings Banksy taxidermy food truck authentic meditation.

Chambray blog put a bird on it scenester mumblecore cray. Hella gluten-free sartorial swag brunch fanny pack four loko DIY banh mi whatever fixie Banksy drinking vinegar dreamcatcher listicle. Viral food truck banjo sartorial bicycle rights slow-carb tote bag PBR, fanny pack pour-over ethical gluten-free locavore. +1 plaid High Life, organic Banksy narwhal typewriter Bushwick whatever yr. Truffaut cold-pressed kale chips, mlkshk distillery Pinterest authentic Intelligentsia. Cred locavore butcher tote bag, Banksy paleo Wes Anderson Intelligentsia pork belly post-ironic health goth. Butcher Godard twee craft beer.</p>

app/views/static_pages/portfolio.html.erb
<% provide(:title, "Portfolio") %>
<h1 class="center">Portfolio</h1>
<p>Chambray blog put a bird on it scenester mumblecore cray. Hella gluten-free sartorial swag brunch fanny pack four loko DIY banh mi whatever fixie Banksy drinking vinegar dreamcatcher listicle. Viral food truck banjo sartorial bicycle rights slow-carb tote bag PBR, fanny pack pour-over ethical gluten-free locavore. +1 plaid High Life, organic Banksy narwhal typewriter Bushwick whatever yr. Truffaut cold-pressed kale chips, mlkshk distillery Pinterest authentic Intelligentsia. Cred locavore butcher tote bag, Banksy paleo Wes Anderson Intelligentsia pork belly post-ironic health goth. Butcher Godard twee craft beer.</p>